name: Test and Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest]
        python-version: [3.9]
        qt-binding: ['pyside2']
        include:
          - os: windows-latest
            python-version: 3.10
            qt-binding: 'pyside6'

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xfixes0 x11-utils
        # Additional dependencies for PySide2
        sudo apt-get install -y libgl1-mesa-dev libglib2.0-0 libegl1 libdbus-1-3 libxkbcommon0 libxkbcommon-x11-0 libxcb-cursor0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox
        pip list

    - name: Debug environment
      run: |
        echo "Current directory: ${{ github.workspace }}"
        dir
        echo "Python version:"
        python --version

    - name: Run tests (Windows)
      if: runner.os == 'Windows'
      run: |
        nox --version
        nox -l
        nox -s test -- --qt-binding=${{ matrix.qt-binding }}

    - name: Run tests (Linux)
      if: runner.os == 'Linux'
      run: |
        nox --version
        nox -l
        # Create XDG runtime directory
        mkdir -p /tmp/runtime-runner
        chmod 700 /tmp/runtime-runner
        # Run with Xvfb with specific configuration
        xvfb-run --auto-servernum --server-args="-screen 0 1280x720x24" nox -s test -- --qt-binding=${{ matrix.qt-binding }}

    - name: Check for coverage file
      run: |
        dir
        if (Test-Path -Path "coverage.xml") {
            echo "Coverage file exists"
            type coverage.xml
        } else {
            echo "Coverage file does not exist"
            echo "Creating dummy coverage file"
            echo '<?xml version="1.0" ?><coverage version="5.5"></coverage>' > coverage.xml
        }

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  maya-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Check Docker
      run: |
        docker --version
        docker info

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Run Maya tests
      run: |
        nox -s maya-test

  blender-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Check Docker
      run: |
        docker --version
        docker info

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox

    - name: Run Blender tests
      run: |
        nox -s blender-test


