name: Test and Lint

on: [push, pull_request]

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'
        cache-dependency-path: '**/pyproject.toml'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nox
        pip list

    - name: Debug environment
      run: |
        echo "Current directory: ${{ github.workspace }}"
        dir
        echo "Python version:"
        python --version

    - name: Run tests
      run: |
        nox --version
        nox -l
        nox -s test

    - name: Check for coverage file
      run: |
        dir
        if (Test-Path -Path "coverage.xml") {
            echo "Coverage file exists"
            type coverage.xml
        } else {
            echo "Coverage file does not exist"
            echo "Creating dummy coverage file"
            echo '<?xml version="1.0" ?><coverage version="5.5"></coverage>' > coverage.xml
        }

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      continue-on-error: true
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false


